In [1]:
from __future__ import print_function
import numpy as np
import h5py
import pandas as pd
import matplotlib.pyplot as plt

with h5py.File('Gonzalez15.VELOCIraptor/iz200/ivol10/galaxies.hdf5','r') as hf:
    data = hf.get('Output001')
    np_data = np.array(data)
    print('Shape of the array Output001: \n', np_data.shape)
    #print('List of items of the output: \n',data.items())
    times =hf.get("Output_Times")
    vdisk=np.array(data.get('vdisk'))
    vhalo=np.array(data.get('vhalo'))
    mcold_atom_bulge=np.array(data.get('mcold_atom_bulge'))
    mcold_mol_bulge =np.array(data.get('mcold_mol_bulge'))
    mstars_bulge    =np.array(data.get('mstars_bulge'))
    mstars_disk     =np.array(data.get('mstars_disk'))
    mchalo          =np.array(data.get('mchalo'))
    mhalo           =np.array(data.get('mhalo'))
    mhhalo          =np.array(data.get('mhhalo'))
    index           =np.array(data.get('index'))
    ihalo           =np.array(data.get('ihhalo'))

    # Checking Vdisk data and Vhalo data
    n_data1=vdisk.shape[0]# they are both the same number
    n_data2=vhalo.shape[0]# check above
    

Shape of the array Output001: 
 (74,)


In [2]:
index

array([ 1,  7,  4, ...,  8, 11, 51], dtype=int32)

In [3]:
#np.mean(index)
np.amax(index)
#np.amin(index)

25264

In [4]:
ihalo

array([1, 1, 1, ..., 1, 1, 1], dtype=int32)

In [5]:
plt.hist(index,25)

(array([ 17043.,   2033.,   1150.,    755.,    581.,    450.,    304.,
           267.,    265.,    210.,    180.,    167.,    124.,    125.,
           104.,     88.,     66.,     61.,     43.,     39.,     47.,
            44.,     27.,     42.,     33.]),
 array([  1.00000000e+00,   1.01152000e+03,   2.02204000e+03,
          3.03256000e+03,   4.04308000e+03,   5.05360000e+03,
          6.06412000e+03,   7.07464000e+03,   8.08516000e+03,
          9.09568000e+03,   1.01062000e+04,   1.11167200e+04,
          1.21272400e+04,   1.31377600e+04,   1.41482800e+04,
          1.51588000e+04,   1.61693200e+04,   1.71798400e+04,
          1.81903600e+04,   1.92008800e+04,   2.02114000e+04,
          2.12219200e+04,   2.22324400e+04,   2.32429600e+04,
          2.42534800e+04,   2.52640000e+04]),
 <a list of 25 Patch objects>)

In [6]:
plt.show()